// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VyFAQ.Database;

namespace VyFAQ.Migrations
{
    [DbContext(typeof(FAQContext))]
    [Migration("20191115175352_FAQDB")]
    partial class FAQDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VyFAQ.Models.FAQ", b =>
                {
                    b.Property<int>("QuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TommelNed")
                        .HasColumnType("int");

                    b.Property<int>("TommelOpp")
                        .HasColumnType("int");

                    b.HasKey("QuestionID");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            QuestionID = 1,
                            Answer = "Ja. Dette koster litt ekstra, og lar seg gjøre mens du kjøper billett.",
                            Category = "Buss",
                            Question = "Kan jeg reservere seter på buss?",
                            TommelNed = 0,
                            TommelOpp = 0
                        },
                        new
                        {
                            QuestionID = 2,
                            Answer = "Dette kommer an på ruten. I ruter som tar mer enn 3 timer stopper vi på steder hvor det er mulig å strekke seg på beina og kjøpe mat og drikke.",
                            Category = "Buss",
                            Question = "Stopper bussen på rasteplasser?",
                            TommelNed = 0,
                            TommelOpp = 0
                        },
                        new
                        {
                            QuestionID = 3,
                            Answer = "Om du har en bruker kan du finne alle billettene dine. Det kan også hende du har en kopi på epost-kontoen du har brukt for å kjøpe billetten.",
                            Category = "Buss",
                            Question = "Jeg har mistet billetten min. Ligger den et sted på siden?",
                            TommelNed = 0,
                            TommelOpp = 0
                        },
                        new
                        {
                            QuestionID = 4,
                            Answer = "Ja. Dette koster litt ekstra, og lar seg gjøre mens du kjøper billett.",
                            Category = "Tog",
                            Question = "Kan jeg reservere seter på Tog?",
                            TommelNed = 0,
                            TommelOpp = 0
                        },
                        new
                        {
                            QuestionID = 5,
                            Answer = "I rushtidene er alt vi har av tilgjengelig materiell i bruk. Vi forsøker å matche etterspørselen med «riktig» kapasitet så langt det lar seg gjøre, likevel er det ikke mulig å tilby sitteplasser til alle. Vi får stadig flere togsett levert fra fabrikk så på sikt øker det muligheten til å kjøre flere avganger med doble togsett.",
                            Category = "Tog",
                            Question = "Hvorfor er det alltid så fullt på toget?",
                            TommelNed = 0,
                            TommelOpp = 0
                        },
                        new
                        {
                            QuestionID = 6,
                            Answer = "Du kan raskt og enkelt gjøre et rutesøk i reiseplanleggeren eller i appen. Du kan også finne rutetider i rutetabellene.",
                            Category = "Tog",
                            Question = "Hvordan finner jeg rutetidene?",
                            TommelNed = 0,
                            TommelOpp = 0
                        },
                        new
                        {
                            QuestionID = 7,
                            Answer = "I situasjoner der du må ta i bruk alternativ transport eller får andre utgifter i forbindelse med forsinkelse eller kansellering av tog, kan du få refundert hele eller deler av utleggene. Dette må gjøres skriftlig med vedlagt dokumentasjon innen tre måneder etter hendelsen.",
                            Category = "Betaling",
                            Question = "Kan jeg få erstatning for merkostnader ved forsinkelse?",
                            TommelNed = 0,
                            TommelOpp = 0
                        },
                        new
                        {
                            QuestionID = 8,
                            Answer = "Alle billetter må refunderes før avgang, du vil ikke ha krav på refusjon etter togavgangen dersom du ikke rekker toget ditt.",
                            Category = "Betaling",
                            Question = "Jeg rakk ikke avgangen. Kan jeg få refundert billetten?",
                            TommelNed = 0,
                            TommelOpp = 0
                        },
                        new
                        {
                            QuestionID = 9,
                            Answer = "Du kan slette og legge til betalingskort ved å logge inn på vy.no og gå til «Min profil». I appen går du til «Profil», så velger du «Betaling».",
                            Category = "Betaling",
                            Question = "Hvordan endrer jeg betalingskortet tilknyttet Vy-profilen min?",
                            TommelNed = 0,
                            TommelOpp = 0
                        });
                });

            modelBuilder.Entity("VyFAQ.Models.RatedThumbsUp", b =>
                {
                    b.Property<int>("RatingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastClickedQuestion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RatingID");

                    b.ToTable("PositiveRatings");
                });

            modelBuilder.Entity("VyFAQ.Models.SubmittedQuestions", b =>
                {
                    b.Property<int>("QuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastClickedQuestion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rating")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubmittedQuestion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuestionID");

                    b.ToTable("SubmittedQuestions");
                });
#pragma warning restore 612, 618
        }
    }
}
